import { FastifyInstance } from 'fastify';
import { prisma } from '../repositories/prisma';
import fs from 'fs';
import { io } from '../server';
import axios from 'axios';
import QRCode from 'qrcode';
import { uploadJson, uploadFromUrl, uploadBuffer, getExtFromUrl, getSignedUrl } from '../services/gcsService';

export default async function wahaWebhookController(fastify: FastifyInstance) {
  fastify.post('/api/v1/webhooks/waha', async (request, reply) => {
    const payload: any = request.body;
    
    // IMMEDIATELY return 200 OK to prevent WAHA webhook timeout (Context Canceled error)
    reply.send({ ok: true });

    // Process everything asynchronously in the background
    (async () => {
      try {
        if (!payload || !payload.session) return;

        const deviceId = payload.session;
        const device = await prisma.device.findUnique({ where: { id: deviceId } });
        if (!device) return;

        const event = payload.event;

      if (event === 'session.status') {
        const status = payload.payload?.status; // SCAN_QR_CODE, WORKING, FAILED
        // console.log(`[WAHA] Session ${deviceId} status changed to ${status}`);
        if (status === 'WORKING') {
           await prisma.device.update({
             where: { id: deviceId },
             data: { status: 'connected', providerConfig: { state: 'CONNECTED' } }
           });
           io.to(`tenant_${device.tenantId}`).emit('connection_update', { device_id: deviceId, status: 'connected' });

           // Simpan session status log ke GCS
           uploadJson(
             { deviceId, status: 'WORKING', tenantId: device.tenantId, timestamp: new Date().toISOString() },
             `sessions/${deviceId}/status_${Date.now()}.json`
           ).catch((e) => console.warn('[GCS] Failed to save session log:', e.message));

        } else if (status === 'SCAN_QR_CODE') {
           // Fetch QR from WAHA and emit
           const WAHA_URL = process.env.WAHA_URL || 'http://localhost:3001';
           const WAHA_API_KEY = process.env.WAHA_API_KEY || 'waha_secret_key';
           
           // Wait 1.5 second for QR to be fully generated by WAHA
           setTimeout(async () => {
             try {
               const res = await axios.get(`${WAHA_URL}/api/${deviceId}/auth/qr?format=raw`, {
                 headers: { 'X-Api-Key': WAHA_API_KEY }
               });
               
               const qrRaw = typeof res.data === 'string' ? res.data : (res.data?.value || res.data?.qr);
               
               if (qrRaw) {
                 const qrBase64 = await QRCode.toDataURL(qrRaw);
                 io.to(`tenant_${device.tenantId}`).emit('qr_update', { device_id: deviceId, qr: qrBase64 });

                 // Simpan session status QR ke GCS
                 uploadJson(
                   { deviceId, status: 'SCAN_QR_CODE', tenantId: device.tenantId, timestamp: new Date().toISOString() },
                   `sessions/${deviceId}/status_${Date.now()}.json`
                 ).catch((e) => console.warn('[GCS] Failed to save QR session log:', e.message));
               } else {
                 console.log(`[WAHA] QR data not found in response`);
               }
             } catch (err: any) {
               console.error('[WAHA] Failed to fetch/emit QR:', err.message, err.response?.data);
             }
           }, 1500);
        } else if (status === 'FAILED') {
           await prisma.device.update({
             where: { id: deviceId },
             data: { status: 'disconnected', providerConfig: { state: 'DISCONNECTED' } }
           });
           io.to(`tenant_${device.tenantId}`).emit('connection_update', { device_id: deviceId, status: 'disconnected' });

           // Simpan session status log ke GCS
           uploadJson(
             { deviceId, status: 'FAILED', tenantId: device.tenantId, timestamp: new Date().toISOString() },
             `sessions/${deviceId}/status_${Date.now()}.json`
           ).catch((e) => console.warn('[GCS] Failed to save session log:', e.message));
        }
      } 
      else if (event === 'message' || event === 'message.any') {
        const msg = payload.payload;
        if (!msg) return;

        // Temporarily log payload to file for debugging
        fs.appendFileSync('scratch/waha_payload.json', JSON.stringify(msg, null, 2) + '\n,\n');

        const isFromMe = msg.fromMe || false;
        
        // WhatsApp sometimes uses @lid (masked numbers) for incoming business messages.
        // Try to get the real number from SenderAlt if it's available and it's not a group.
        let remoteJid = msg.chatId || msg.from;
        const isGroup = remoteJid?.endsWith('@g.us') || (msg.from && msg.from.endsWith('@g.us')) || (msg.chatId && msg.chatId.endsWith('@g.us')) || msg._data?.Info?.IsGroup || false;
        if (!isGroup && remoteJid?.includes('@lid')) {
           const alt = msg._data?.Info?.SenderAlt || msg._data?.Info?.ReceiverAlt || msg._data?.SenderAlt || msg.senderAlt;
           if (alt) {
              remoteJid = alt;
           }
        }

        // Normalize @s.whatsapp.net to @c.us for our internal consistency
        if (remoteJid && remoteJid.includes('@s.whatsapp.net')) {
           remoteJid = remoteJid.replace('@s.whatsapp.net', '@c.us');
        }
        
        const text = msg.body || '';

        // Determine proper initial status from WAHA ack payload
        let initialStatus = 'delivered';
        if (isFromMe) {
          const ackName = msg.ackName;
          const ack = msg.ack;
          if (ackName === 'READ' || ackName === 'PLAYED' || ack === 3 || ack === 4) initialStatus = 'read';
          else if (ackName === 'DELIVERED' || ackName === 'DEVICE' || ack === 2) initialStatus = 'delivered';
          else if (ackName === 'SERVER' || ackName === 'SENT' || ack === 1) initialStatus = 'sent';
          else if (ackName === 'ERROR' || ack === -1) initialStatus = 'failed';
          else initialStatus = 'read'; // For historical synced messages, default to 'read'
        }

        // Save Contact
        if (!isGroup) {
          // Individual Contact: update pushName
          const pushName = msg.pushName || msg._data?.notifyName || msg._data?.Info?.PushName;
          if (pushName) {
             await prisma.contact.upsert({
               where: { deviceId_remoteJid: { deviceId, remoteJid } },
               create: { tenantId: device.tenantId, deviceId, remoteJid, pushName },
               update: { pushName }
             });
          }
        } else {
          // Group Chat (@g.us):
          // 1. Never overwrite group contact name with participant sender's pushName!
          const groupName = msg._data?.chat?.name || msg._data?.Info?.Subject || msg._data?.groupSubject || msg.chat?.name;
          if (groupName) {
             await prisma.contact.upsert({
               where: { deviceId_remoteJid: { deviceId, remoteJid } },
               create: { tenantId: device.tenantId, deviceId, remoteJid, pushName: groupName },
               update: { pushName: groupName }
             });
          }

          // 2. Save individual participant contact info if present
          const participantJid = msg.participant || msg.author || msg._data?.author || msg._data?.participant;
          const participantPushName = msg.pushName || msg._data?.notifyName || msg._data?.Info?.PushName;
          if (participantJid && participantPushName && !participantJid.endsWith('@g.us')) {
             await prisma.contact.upsert({
               where: { deviceId_remoteJid: { deviceId, remoteJid: participantJid } },
               create: { tenantId: device.tenantId, deviceId, remoteJid: participantJid, pushName: participantPushName },
               update: { pushName: participantPushName }
             });
          }
        }

        // Simpan media (gambar/audio/dokumen) ke GCS jika ada
        const isMediaStr = ['image', 'video', 'audio', 'document', 'sticker'].includes(msg.type) || msg._data?.Info?.Type === 'media' || ['image', 'video', 'audio', 'document', 'sticker'].includes(msg._data?.Info?.MediaType);
        const isMediaMsg = msg.hasMedia || isMediaStr || msg.file?.url || msg.media?.url || msg.mediaUrl;
        
        let initialMediaUrl: string | null = null;
        let initialMediaPath: string | null = null;
        let finalMessageType = isMediaMsg ? 'media' : 'text';

        if (isMediaMsg) {
          const b64Thumb = msg._data?.Message?.imageMessage?.JPEGThumbnail || msg._data?.RawMessage?.imageMessage?.JPEGThumbnail || msg._data?.Message?.videoMessage?.jpegThumbnail || msg._data?.RawMessage?.videoMessage?.jpegThumbnail || msg.media?.thumbnail;
          let directUrl = msg.file?.url || msg.media?.url || msg.mediaUrl || msg._data?.mediaUrl;
          
          if (directUrl && directUrl.includes('?')) {
            directUrl = directUrl.split('?')[0];
          }

          if (b64Thumb && !b64Thumb.startsWith('data:')) {
            initialMediaUrl = `data:image/jpeg;base64,${b64Thumb}`;
            initialMediaPath = directUrl || null;
          } else if (b64Thumb && b64Thumb.startsWith('data:')) {
            initialMediaUrl = b64Thumb;
            initialMediaPath = directUrl || null;
          } else {
            initialMediaUrl = directUrl || null;
            initialMediaPath = directUrl || null;
          }

          // Fallback download from WAHA if we have NO direct URL and NO base64 thumbnail
          if (!initialMediaPath && !initialMediaUrl) {
            const wahaUrl = process.env.WAHA_URL || 'http://localhost:3001';
            const wahaApiKey = process.env.WAHA_API_KEY || 'waha_secret_key';
            const downloadUrl = `${wahaUrl}/api/${deviceId}/messages/${msg.id}/download`;

            try {
              const response = await axios.get(downloadUrl, {
                headers: {
                  'X-Api-Key': wahaApiKey,
                  'Accept': 'application/json'
                },
                responseType: 'arraybuffer'
              });

              let buffer: Buffer;
              let mimetype = 'application/octet-stream';
              let filename = `${msg.id}.bin`;

              if ((response.headers['content-type'] as string)?.includes('application/json')) {
                 const data = JSON.parse(response.data.toString('utf8'));
                 buffer = Buffer.from(data.data || data.base64 || '', 'base64');
                 mimetype = data.mimetype;
                 filename = data.filename || `${msg.id}`;
              } else {
                 buffer = Buffer.from(response.data);
                 mimetype = (response.headers['content-type'] as string) || mimetype;
                 const mimeToExt: any = {
                   'image/jpeg': '.jpg', 'image/png': '.png', 'image/webp': '.webp',
                   'video/mp4': '.mp4', 'audio/mpeg': '.mp3', 'audio/ogg': '.ogg',
                   'application/pdf': '.pdf'
                 };
                 filename = `${msg.id}${mimeToExt[mimetype] || '.bin'}`;
              }

              const gcsPath = `inbound-media/${deviceId}/${filename}`;
              const downloadedGcsUrl = await uploadBuffer(buffer, gcsPath, mimetype);
              initialMediaPath = downloadedGcsUrl;
              if (!initialMediaUrl) initialMediaUrl = downloadedGcsUrl;
            } catch (mediaErr: any) {
              console.warn(`[WAHA WARN] Failed to download inbound media. URL: ${downloadUrl}`);
              console.warn(`[WAHA WARN] Error:`, mediaErr.message);
            }
          }
        }

        // Check if message already exists to avoid duplicate socket emissions
        const existingMsg = await prisma.chatMessage.findUnique({
          where: { deviceId_remoteJid_messageId: { deviceId, remoteJid, messageId: msg.id } }
        });

        let chatMsg;
        try {
          // Save Message
          chatMsg = await prisma.chatMessage.upsert({
            where: { deviceId_remoteJid_messageId: { deviceId, remoteJid, messageId: msg.id } },
            create: {
              tenantId: device.tenantId,
              deviceId,
              remoteJid,
              messageId: msg.id,
              isFromMe,
              text,
              messageType: finalMessageType as any,
              mediaUrl: initialMediaUrl,
              mediaPath: initialMediaPath,
              timestamp: new Date(msg.timestamp ? msg.timestamp * 1000 : Date.now()),
              status: initialStatus as any
            },
            update: {
              status: undefined
            }
          });
        } catch (e: any) {
          if (e.code === 'P2002') {
             console.log(`[Webhook] Message ${msg.id} already inserted concurrently. Ignoring duplicate.`);
             return;
          }
          throw e;
        }

        // Notify UI only if it's a new message
        if (!existingMsg) {
          io.to(`tenant_${device.tenantId}`).emit('chat_message', {
             device_id: deviceId,
             remoteJid,
             message: chatMsg
          });
        }
      }
      else if (event === 'message.ack') {
        const msgAck = payload.payload;
        if (!msgAck) return;

        // WAHA message.ack structure:
        // ack: number (status code)
        // ackName: string ('SENT', 'DELIVERED', 'READ', 'PLAYED', 'ERROR')
        // id: message ID inside _data or direct
        
        const rawId = typeof msgAck.id === 'string' ? msgAck.id : msgAck.id?._serialized;
        let serializedId = msgAck.id?._serialized || (typeof msgAck.id === 'string' ? msgAck.id : null);
        let shortId = msgAck.id?.id || (msgAck._data?.MessageIDs && msgAck._data.MessageIDs[0]) || msgAck.id;
        
        // If shortId is actually a serialized string, extract the real short ID (after last underscore)
        if (typeof shortId === 'string' && shortId.includes('_')) {
           const parts = shortId.split('_');
           shortId = parts[parts.length - 1];
        }

        const ackName = msgAck.ackName; // e.g. 'DELIVERED' or 'DEVICE'
        
        console.log(`[WAHA] Received message.ack for shortId:${shortId} / rawId:${rawId} with status ${ackName}`);

        let newStatus = 'sent';
        if (ackName === 'DELIVERED' || ackName === 'DEVICE') newStatus = 'delivered';
        else if (ackName === 'READ' || ackName === 'PLAYED') newStatus = 'read';
        else if (ackName === 'ERROR') newStatus = 'failed';
        else if (ackName === 'SERVER') newStatus = 'sent';

        // Try to find the message in DB using case-insensitive matching (PostgreSQL requirement)
        let chatMsg = null;
        if (serializedId) {
          chatMsg = await prisma.chatMessage.findFirst({
            where: { messageId: { equals: serializedId, mode: 'insensitive' } }
          });
        }

        if (!chatMsg && shortId) {
           chatMsg = await prisma.chatMessage.findFirst({
             where: {
               OR: [
                 { messageId: { equals: shortId, mode: 'insensitive' } },
                 { messageId: { endsWith: shortId, mode: 'insensitive' } },
                 { messageId: { contains: shortId, mode: 'insensitive' } }
               ]
             }
           });
        }

        if (chatMsg) {
           await prisma.chatMessage.update({
             where: { id: chatMsg.id },
             data: { status: newStatus as any }
           });

           console.log(`[WAHA SUCCESS] Updated message ${chatMsg.id} (${chatMsg.messageId}) status to '${newStatus}' in DB`);

           io.to(`tenant_${device.tenantId}`).emit('message_status_update', {
             device_id: deviceId,
             remoteJid: chatMsg.remoteJid,
             messageId: chatMsg.messageId,
             status: newStatus
           });
        } else {
           console.log(`[WAHA WARN] Message shortId:${shortId} / rawId:${rawId} not found in DB.`);
        }
      }
      } catch (err: any) {
        console.error('WAHA Async Webhook error:', err.message);
      }
    })();
  });

  fastify.get('/api/v1/debug/messages', async (request, reply) => {
    const messages = await prisma.chatMessage.findMany({
      orderBy: { createdAt: 'desc' },
      take: 10
    });
    return reply.send(messages);
  });
}
